version: '3.8'

services:
  # This runs your Database
  postgres:
    image: postgres:15
    container_name: medical_warehouse_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: